#!/usr/bin/env fish

function logger-warn
  set_color magenta
  echo "$prefix [Warn] $argv[1..-1]"
  set_color normal
end
function logger-error
  set_color red
  echo "$prefix [Error] $argv[1..-1]"
  set_color normal
end
function logger-info
  set_color normal
  echo "$prefix [Info] $argv[1..-1]"
  set_color normal
end
function logger-debug
  set_color yellow
  echo "$prefix [Debug] $argv[1..-1]"
  set_color normal
end
function logger-success
  set_color green
  echo "$prefix [Successed] $argv[1..-1]"
  set_color normal
end
function logger -d "a lib to print msg quickly"
switch $argv[1]
case 0
  logger-info $argv[2..-1]
case 1
  logger-success $argv[2..-1]
case 2
  logger-debug $argv[2..-1]
case 3
  logger-warn $argv[2..-1]
case 4
  logger-error $argv[2..-1]
end
end

function injector
    if command -q -v ctpkg
    else
        init
    end
    logger 0 "We're going to install the basic system,continue?"
    read -P "$prefix [Press enter to confirm,Ctrl+C to abort]"
    logger 0 "Grabbing the package index..."
    ctpkg grab upg
    logger 0 "Start processing packages..."
    ctpkg grab center-plymouth-theme center-grub-theme center-id ctcontainer ctpkg neofetch progynosh ctutils
    logger 0 "Processed."
end

function init
curl -s -L -o ctpkg https://cdngit.ruzhtw.top/pkghub/ctpkg
fish ctpkg grab ctpkg
rm ctpkg
end
echo Build_Time_UTC=2022-03-19_06:36:54
set prefix [CenterLinux-Injector]
switch $argv[1]
    case injector
        injector
    case v
        logger 0 "Corleone@build1"
    case h help "*"
        logger 0 "Use ./app injector for cli guide-elf"
end
